#!/bin/bash

#made by r3d_f1lc0n 02/12/22


red=`tput setaf 1`
reset=`tput sgr0`

echo "[+] ${red} enter file name:${reset} "
read file

lines=$(wc $file)

length=${lines:1:3}


cat $file | while read line;
do
	printf "\x$(printf %x $line)"
done
